- name: Build and deploy
  id: builddeploy
  uses: Azure/static-web-apps-deploy@v1
  with:
    azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
    repo_token: ${{ secrets.GITHUB_TOKEN }}
    action: "upload"
    app_location: "/" # Ou a pasta onde está seu index.html
    api_location: "" # Deixe em branco, pois o backend está em outro serviço
    output_location: "" # Deixe em branco, pois não há passo de build
